# Generated by Django 4.2.4 on 2023-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='gal'),
        ),
    ]
